FROM node:20-slim

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN apt-get update && apt-get install -y openssl
RUN npm install
RUN npm run db:generate
RUN npm run build

CMD ["npm", "run", "start-user-app"]
